elastic search is not up so fix the issue
[2026-08-31T10:38:05,726][ERROR][o.e.b.Elasticsearch      ] [es01] fatal exception while booting Elasticsearch
java.lang.IllegalStateException: failed to load plugin x-pack-esql due to jar hell
        at org.elasticsearch.server@9.2.4-SNAPSHOT/org.elasticsearch.plugins.PluginsUtils.checkBundleJarHell(PluginsUtils.java:352)
        at org.elasticsearch.server@9.2.4-SNAPSHOT/org.elasticsearch.plugins.PluginsLoader.createPluginsLoader(PluginsLoader.java:220)
        at org.elasticsearch.server@9.2.4-SNAPSHOT/org.elasticsearch.plugins.PluginsLoader.createPluginsLoader(PluginsLoader.java:185)
        at org.elasticsearch.server@9.2.4-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:248)
        at org.elasticsearch.server@9.2.4-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:99)
Caused by: java.lang.IllegalStateException: jar hell!
class: org.slf4j.ILoggerFactory